### ISSUE TITLE
replace exit() -> sys.exit()

### ISSUE THREAD

**Issue by lokiuox** [staresc/staresc#140]
staresc crashes when exiting because exit() should not be used in scripts.    
Check this answer for details about this: https://stackoverflow.com/a/6501134

**Comment by 5amu** [comment]
Good catch, it is legacy code on our end...

**Comment by 5amu** [comment]
Solved in commit [88cd9a4a9d2c7a1fd58e773d6c2f3344bcbeb696](https://github.com/staresc/staresc/commit/88cd9a4a9d2c7a1fd58e773d6c2f3344bcbeb696) on branch 138-refactoring, will be merged asap
